apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-proxy-deployment
    typ: proxy
  name: nginx-proxy-deployment
  annotations:
    kubernetes.io/change-cause: "Changed image from ngixn:1.9 to nginx:1.17"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-proxy-deployment
      typ: proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-proxy-deployment
        typ: proxy
    spec:
      containers:
      - image: nginx:1.17
        name: nginx
        resources: {}
status: {}
